spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: idol-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:29092

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
