spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: idol-redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
