rootProject.name = 'idol'
include 'config-server'
include 'discovery-service'
include 'api-gateway'
include 'auth-service'
include 'user-service'
include 'board-service'
include 'chat-service'
include 'vote-service'
include 'payment-service'
include 'ranking-service'
include 'notify-service'
include 'search-service'
include 'concert-service'
include 'fanout-service'
include 'subscription-service'
