server:
  port: 8088

spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:mysql://localhost:3307/idol_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # OSIV 끄기

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      notify-request: notify-request-topic # 추가됨
      payment-requested: payment.requested # 추가됨

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

toss:
  secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R

# Toss Payments 설정
toss:
  secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R

