spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://idol-db:3306/idol_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: idol-redis
      port: 6379
    mongodb:
      host: idol-mongo
      port: 27017
      database: idol_user_view

  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
