server:
  port: 8097

spring:
  application:
    name: board-service

  datasource:
    url: jdbc:mysql://localhost:3307/idol_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # OSIV 끄기

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      notify-request: notify-request-topic # 추가됨

# ?? ??? ??? ? (FeignClient?? ??? ??)
internal:
  key: ${INTERNAL_KEY:INTERNAL_SECRET_KEY}

# FeignClient ?? ??? ?? (?? ?? ??)
clients:
  user-service:
    url: http://localhost:8082
  subscription-service:
    url: http://localhost:8088


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

