spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://idol-db:3306/idol_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: idol-redis
      port: 6379

clients:
  user-service:
    url: http://user-service:8082
  subscription-service:
    url: http://subscription-service:8088

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
