server:
  port: 8095

spring:
  application:
    name: fanout-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fanout-request-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

fanout:
  topics:
    request: notify-request-topic
    fanout: notify-fanout-topic
  consumer:
    group-id: fanout-request-group

clients:
  user-service:
    url: http://localhost:8082
  subscription-service:
    url: http://localhost:8088


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

